### ISSUE TITLE
/departure/station/ not working

### ISSUE THREAD

**Issue by elcool0r** [kevcodez/Metronom-REST-API#2]
Thanks for the api, it's working fine except of the endpoint /departure/station/:

curl http://localhost:8080/departure/station/Tostedt
{"timestamp":"2019-01-22T05:45:12.856+0000","status":500,"error":"Internal Server Error","message":"Parameter specified as non-null is null: method de.kevcodez.metronom.rest.DeparturesWithAlertResource.findByStation, parameter station","path":"/departure/station/Tostedt"}

Also do you know if there are more endpoints on the original api path? The metronom app is showing travel times & train models too.

**Comment by kevcodez** [comment]
Hey @elcool0r , thanks for reporting. 

I'll try to have a look at it in the upcoming days. If you found the issue, feel free to provide a PR.

Regards,
Kevin

**Comment by elcool0r** [comment]
I'm still trying to figure out the framework but my programming skills are pretty much only writing some ruby code :D

**Comment by kevcodez** [comment]
@elcool0r Fixed it.

`curl http://localhost:8080/departure/station/Tostedt` 

now works as intended.
