### ISSUE TITLE
Unexpected error occurred in scheduled task.

### ISSUE THREAD

**Issue by Floyer007** [kevcodez/Metronom-REST-API#3]
The URL for livedata requires a login now or moved.

java.io.IOException: Server returned HTTP response code: 500 for URL: https://www.der-metronom.de/livedata/etc?type=troublelist&_=1538252265246

**Comment by kevcodez** [comment]
@Floyer007 I haven't touched this project in a long time and I no longer use the Metronom as I moved. Feel free to fork this project or provide a PR to fix this.

Initially, I went to the Metronom website and just inspected the network traffic using the Google Chrome console. Back then, it was fairly easy to "reverse engineer".

**Comment by Floyer007** [comment]
Unfortunately I don't have the time to maintain or modify it right now.
I have to learn kotlin first :D

Thank you for your tip with the console!
Seems I found the new URLs now. Probably will take a look at it in the future.

The URLs contains the "&product=metronom" now.

**Comment by Floyer007** [comment]
For anyone who has the same issue: My fork has at least a working alert yet.
